baseURL = "https://dmitriyvovk.com"
languageCode = "en-us"
title = "Dmitriy Vovk personal blog"
theme = "cactus"
disqusShortname = "dmitriyvovk"
googleAnalytics = "G-ZTJ277R2VL"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog posts"
url = "/posts"
weight = 2

[[menu.books]]
name = "Books"
url = "/books"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "The aim of this blog is to use Feynman technique for learning something and cover my own gaps by expalining things to the public. As the benefit, the blog could leed to interesting conversations and new discoveries with people all around the world. Thank you for reading it!"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 1 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/worldcompass"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dmitriy-vovk-14a5b4180/"
  [[params.social]]
    name = "email"
    link = "vovk.dmitriy9@gmail.com"  # no need for "mailto:" in the head
